### ISSUE TITLE
images print as black squares

### ISSUE THREAD

**Issue by sulligaffer** [matt123p/TinyCAD#26] opened 2021-03-15 17:35 UTC
[TinyCAD test.zip](https://github.com/matt123p/TinyCAD/files/6143354/TinyCAD.test.zip)
I am running version 3.00.02 on windows 10 platform.  When I try to print this file to my printer or to pdf, the image is replaced by a black rectangle.  ----  We have three machines running Windows 10 pro.  Two of them do not print images.  The third we just took out of the closet just for testing and it seems to work.  The one that works has been in the closet since October and we are keeping it disconnected from the Internet in case one of the windows updates since October might be the problem.  --- One of the non-working ones is version 19041.867.  The one that works just says version 19041
Update:  I found a windows 10 pro machine that is on version 19041.572 that can print the images

**Comment by PL1446** [comment] 2021-03-16 09:50
I have exactly the same problem with printning pictures as **sulligaffer**. We run 3.00.02 on three different computers on Windows 10 plattform, all unable to print pictures.

**Comment by pjlm3105** [comment] 2021-03-16 12:23
Hi, i have the same problem... 
It could be a windows actualization issue?
I already try diferent pdf printers without any luck

**Comment by AFIDclan** [comment] 2021-03-16 17:35
Yeah same here

**Comment by pjlm3105** [comment] 2021-03-16 19:36
> I have exactly the same problem with printning pictures as **sulligaffer**. We run 3.00.02 on three different computers on Windows 10 plattform, all unable to print pictures.
> EDIT: I now get the same result printing on paper, both Toshiba copy machine and HP printer.

The windows version of all computers are windows PRO?

**Comment by PL1446** [comment] 2021-03-17 06:07
> > I have exactly the same problem with printning pictures as **sulligaffer**. We run 3.00.02 on three different computers on Windows 10 plattform, all unable to print pictures.
> > EDIT: I now get the same result printing on paper, both Toshiba copy machine and HP printer.
> 
> The windows version of all computers are windows PRO?

All comupters are Windows 10 Pro. Two of them are Windows version 20H2 and OS version 19042.867. The remaining computer is version 2004 / 19041.867.

**Comment by PL1446** [comment] 2021-03-17 13:59
I've made a discovery. The very first print job after starting TinyCAD is partially working. When I print a circuit diagram with five pages (wich all have pictures) the pictures come out allright on page 2 to 5 but page 1 will have a black square. This only works once, you need to reboot TinyCAD to make it work again.

**Comment by pjlm3105** [comment] 2021-03-17 15:14
I already download the 3.03 and the problem is corrected

A quarta, 17/03/2021, 13:59, PL1446 ***@***.***> escreveu:

**Comment by matt123p** [comment] 2021-03-18 07:43
This should be fixed in 3.0.3, so I am closing.

**Closed by matt123p** 2021-03-18 07:43 UTC
